library(readr)
Project_dataset <- read.csv("C:/Users/30987/Desktop/DMG/Project dataset.zip")
names(Project_dataset)
str(Project_dataset)
Project_dataset$icl_class<-as.factor(Project_dataset$icl_class)
Project_dataset$patent<-as.factor(Project_dataset$patent)
Project_dataset$gvkey<-as.factor(Project_dataset$gvkey)
head(Project_dataset)
t(summary(Project_dataset))
summary(Project_dataset)
sum(is.na(Project_dataset))
hist(Project_dataset$at_1)
hist(Project_dataset$at0)
hist(Project_dataset$at1)
barplot(Project_dataset$at_1)
library(plotrix)
l<-list(Project_dataset$at_1,Project_dataset$at0,Project_dataset$at1)
l1<-list(Project_dataset$ni_1,Project_dataset$ni0,Project_dataset$ni1)
l2<-list(Project_dataset$sale_1,Project_dataset$sale0,Project_dataset$sale1)
??multhist
multhist(l,main="Comparing Total Assets of the patent assignee")
multhist(l1,main="Comparing Net Income of the patent assignee")
multhist(l2,main="Comparing Sales of the patent assignee")
boxplot(Project_dataset[,-c(1:4)],horizontal=TRUE)
boxplot(Project_dataset[,c(5:7)],horizontal = TRUE,main="Comparing Total Assets of the patent assignee")
boxplot(Project_dataset[,c(7:9)],horizontal = TRUE,main="Comparing Net Income of the patent assignee")
boxplot(Project_dataset[,c(10:12)],horizontal = TRUE,main="Comparing Sales of the patent assignee")
plot(Project_dataset$icl_class,Project_dataset$at_1)
barplot(Project_dataset$group*Project_dataset$ni_1)
Project_dataset$group <- (str_extract(Project_dataset$icl_class, "[aA-zZ]+"))
Project_dataset$group<-as.factor(Project_dataset$group)
A <- as.matrix(Project_dataset[ which(Project_dataset$group =='A'),5])
B <- as.matrix(Project_dataset[ which(Project_dataset$group =='B'),5])
C <- as.matrix(Project_dataset[ which(Project_dataset$group =='C'),5])
D <- as.matrix(Project_dataset[ which(Project_dataset$group =='D'),5])
E <- as.matrix(Project_dataset[ which(Project_dataset$group =='E'),5])
F <- as.matrix(Project_dataset[ which(Project_dataset$group =='F'),5])
G <- as.matrix(Project_dataset[ which(Project_dataset$group =='G'),5])
H <- as.matrix(Project_dataset[ which(Project_dataset$group =='H'),5])
I <- as.matrix(Project_dataset[ which(Project_dataset$group =='I'),5])
M <- as.matrix(Project_dataset[ which(Project_dataset$group =='M'),5])
P <- as.matrix(Project_dataset[ which(Project_dataset$group =='P'),5])
Q <- as.matrix(Project_dataset[ which(Project_dataset$group =='Q'),5])
R <- as.matrix(Project_dataset[ which(Project_dataset$group =='R'),5])
S <- as.matrix(Project_dataset[ which(Project_dataset$group =='S'),5])
X <- as.matrix(Project_dataset[ which(Project_dataset$group =='X'),5])
l4<-list(A,B,C,D,E,F,G,H,I,M,P,Q,R,S,X)
multhist(l4,main="Comparing Total Assets of the patent assignee")

A1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='A'),8])
B1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='B'),8])
C1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='C'),8])
D1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='D'),8])
E1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='E'),8])
F1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='F'),8])
G1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='G'),8])
H1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='H'),8])
I1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='I'),8])
M1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='M'),8])
P1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='P'),8])
Q1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='Q'),8])
R1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='R'),8])
S1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='S'),8])
X1 <- as.matrix(Project_dataset[ which(Project_dataset$group =='X'),8])
l5<-list(A1,B1,C1,D1,E1,F1,G1,H1,I1,M1,P1,Q1,R1,S1,X1)
multhist(l5,main="Comparing Net Income of the patent assignee")

A2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='A'),11])
B2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='B'),11])
C2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='C'),11])
D2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='D'),11])
E2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='E'),11])
F2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='F'),11])
G2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='G'),11])
H2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='H'),11])
I2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='I'),11])
M2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='M'),11])
P2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='P'),11])
Q2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='Q'),11])
R2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='R'),11])
S2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='S'),11])
X2 <- as.matrix(Project_dataset[ which(Project_dataset$group =='X'),11])
l6<-list(A2,B2,C2,D2,E2,F2,G2,H2,I2,M2,P2,Q2,R2,S2,X2)
multhist(l6,main="Comparing Sales of the patent assignee")


A3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='A'),17])
B3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='B'),17])
C3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='C'),17])
D3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='D'),17])
E3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='E'),17])
F3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='F'),17])
G3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='G'),17])
H3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='H'),17])
I3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='I'),17])
M3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='M'),17])
P3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='P'),17])
Q3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='Q'),17])
R3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='R'),17])
S3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='S'),17])
X3 <- as.matrix(Project_dataset[ which(Project_dataset$group =='X'),17])
l7<-list(A3,B3,C3,D3,E3,F3,G3,H3,I3,M3,P3,Q3,R3,S3,X3)
multhist(l7,main="Standard Industrial Classification (SIC)")

data1<-(na.omit(Project_dataset))
names(data1)
summary(data1)




data3 <- as.matrix(data1[ which((data1$sic)>1999 & (data1$sic)<4000),])



# #nonhirarchial clustering
# k<-kmeans(scale(data[,-c(1:4)]),3)
# names(k)
# plot(data[,c(6,9)],col=k$cluster)
# plot(scale(data[,-c(1:4)]),col=(k$cluster+1),main="k-means clustering results with k=3",xlab=" ",ylab=" ",pch=20,cex=2)
# 
# k1 <- kmeans(scale(wine[,-1]),3,nstart=20)
# k1
# plot(scale(wine[,-1]),col=(k1$cluster+1),main="k-means clustering results with k=3",xlab=" ",ylab=" ",pch=20,cex=2)
# 
# ######hirarchial clustering#####################
# ################################################
# 
# 
# d1 <- dist(scale(wine[,-1]), method = "euclidean")
# hc <- hclust(d1,method="complete")
# hc.average<-hclust(d1,method="average")
# hc.single<-hclust(d1,method="single")
# 
# plot(hc,main="complete linkage",xlab=" ",sub=" ",cex=.9)
# plot(hc.average,main="average linkage",xlab=" ",sub=" ",cex=.9)
# plot(hc.single,main="single linkage",xlab=" ",sub=" ",cex=.9)
# 
# #plot(hc,labels=wine$class)
# #plot(hc,labels=wine$class,hang=-1)
# #plot(hc.average)
# #plot(hc.average,labels=wine$class)
# #plot(hc.average,labels=wine$class,hang=-1)
# complete <-cutree(hc,3)
# average <-cutree(hc.average,3)
# single <-cutree(hc.single,3)
# table(complete,as.factor(wine[,1]))
# table(average,as.factor(wine[,1]))
# table(single,as.factor(wine[,1]))
# rect.hclust(hc,3,which=c(1,2,3),border=3:4)
# aggregate(wine[,-1],list(m.d),mean)
# library(cluster)
# #silhouette plot
# plot(silhouette(cutree(hc,3),d1))
# plot(silhouette(cutree(hc.average,3),d1))
# #scree plot
# ssw<-(nrow(wine[,-1])-1)*sum(apply(wine[,-1],2,var))
# for (i in 2:20)ssw[i]<-sum(kmeans(wine[,-1],centers=i)$withinss)
# plot(1:20,ssw,type="b",main="scree plot")
# #To check if 4 clusters are good to understand the data
# k3<-kmeans(scale(wine[,-1]),4,nstart = 20)
# plot(scale(wine[,-1]),col=(k3$cluster+1),main="k-means clustering results with k=4",xlab=" ",ylab=" ",pch=20,cex=2)
# k3
# ##k3$betweeness>k1$betweenness So 4 clusters is good to understand this data
# 
# ##########################