library(readr)
Project_dataset <- read.csv("C:/Users/30987/Desktop/DMG/Project dataset.zip")
names(Project_dataset)
str(Project_dataset)
Project_dataset$icl_class<-as.factor(Project_dataset$icl_class)
Project_dataset$patent<-as.factor(Project_dataset$patent)
Project_dataset$gvkey<-as.factor(Project_dataset$gvkey)
head(Project_dataset)
t(summary(Project_dataset))
summary(Project_dataset)
sum(is.na(Project_dataset))
data1<-(na.omit(Project_dataset))
names(data1)
summary(data1)
data3 <-(data1[ which((data1$sic)>1999 & (data1$sic)<4000),])
str(data3)
summary(data3$sic)

data3$group <- (str_extract(data3$icl_class, "[aA-zZ]+"))
data3$group<-unlist(as.factor(data3$group))
data3$ni<-data3$ni1-data3$ni_1
data3$sale<-data3$sale1-data3$sale_1
data3$xrd<-(data3$xrd_1+data3$xrd0+data3$xrd1)/3
data4<-data3[,c(2,3,4,17,18,19,20)]
data4$group<-(factor(data4$group))
data4$group<-(factor(unlist(data4$group)))
str(data4)
A<- (data4[ which(data4$group =='A'),])
B<- (data4[ which(data4$group =='B'),])
C<- (data4[ which(data4$group =='C'),])
D<- (data4[ which(data4$group =='D'),])
E<- (data4[ which(data4$group =='E'),])
F<- (data4[ which(data4$group =='F'),])
G<- (data4[ which(data4$group =='G'),])
H<- (data4[ which(data4$group =='H'),])
data6<-rbind(G,H)
#data7<-data6[-which(data6$group==''),]

#library(ade4)
#data5<-acm.disjonctif(as.data.frame(data6[,5]))
#dim(data5)
#Edata<-dummy.data.frame(data4,names="group",omit.constants=FALSE)
#data6<-cbind(scale(data4[,-c(1,5)]),data5)
citations <- read_csv("E:/DMG/citations_2004.csv")
Merged_data<-merge(data6,citations,by.x="patent",by.y="citing")
dim(Merged_data)
Merged_data$group1 <- (str_extract(Merged_data$cited_icl, "[aA-zZ]+"))
Merged_data$group1<-unlist(as.factor(Merged_data$group1))
Merged_data$group1<-(factor(Merged_data$group1))
Merged_data$group1<-(factor(unlist(Merged_data$group1)))
str(Merged_data)
A<- (Merged_data[ which(Merged_data$group1 =='A'),])
B<- (Merged_data[ which(Merged_data$group1 =='B'),])
C<- (Merged_data[ which(Merged_data$group1 =='C'),])
D<- (Merged_data[ which(Merged_data$group1 =='D'),])
E<- (Merged_data[ which(Merged_data$group1 =='E'),])
F<- (Merged_data[ which(Merged_data$group1 =='F'),])
G<- (Merged_data[ which(Merged_data$group1 =='G'),])
H<- (Merged_data[ which(Merged_data$group1 =='H'),])
View(Merged_data)
table(Merged_data$group,Merged_data$group1)[c(7,8),]


