library(readr)
Project_dataset <- read.csv("C:/Users/30987/Desktop/DMG/Project dataset.zip")
names(Project_dataset)
str(Project_dataset)
Project_dataset$icl_class<-as.factor(Project_dataset$icl_class)
Project_dataset$patent<-as.factor(Project_dataset$patent)
Project_dataset$gvkey<-as.factor(Project_dataset$gvkey)
head(Project_dataset)
t(summary(Project_dataset))
summary(Project_dataset)
sum(is.na(Project_dataset))
data1<-(na.omit(Project_dataset))
names(data1)
summary(data1)
data3 <-(data1[ which((data1$sic)>1999 & (data1$sic)<4000),])
str(data3)
summary(data3$sic)

data3$group <- (str_extract(data3$icl_class, "[aA-zZ]+"))
data3$group<-unlist(as.factor(data3$group))
data4<-data3[,c(4,10,13,14,18)]
data4$group<-(factor(data4$group))
data4$group<-(factor(unlist(data4$group)))
str(data4)
A<- (data4[ which(data4$group =='A'),])
B<- (data4[ which(data4$group =='B'),])
C<- (data4[ which(data4$group =='C'),])
D<- (data4[ which(data4$group =='D'),])
E<- (data4[ which(data4$group =='E'),])
F<- (data4[ which(data4$group =='F'),])
G<- (data4[ which(data4$group =='G'),])
H<- (data4[ which(data4$group =='H'),])
data6<-rbind(G,H)
data7<-data6[-which(data6$group==''),]

library(ade4)
data5<-acm.disjonctif(as.data.frame(data6[,5]))
dim(data5)
#Edata<-dummy.data.frame(data4,names="group",omit.constants=FALSE)
data6<-cbind(scale(data4[,-c(1,5)]),data5)


